"""tools/pr_screenshots.py: the comment markdown, which files it takes, its arguments, and the git part against a
throwaway bare repository standing in for origin (no network)."""
import importlib.util
import io
import subprocess
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("pr_screenshots", ROOT / "tools" / "pr_screenshots.py")
assert _spec and _spec.loader
ps = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ps)

TRAILERS = ["Co-Authored-By: Claude Sonnet 5.5 <noreply@anthropic.com>", "Claude-Session: https://example.test/s"]


def run(cwd, *args):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True).stdout


class Markdown(unittest.TestCase):
    NAMES = ["budget-desktop-top.png", "budget-phone-top.png", "budget-tablet-top.png", "setup-phone-top.png"]

    def test_headings_per_width_in_order_with_raw_urls_and_the_footer(self):
        md = ps.comment_markdown(42, self.NAMES)
        self.assertLess(md.index("**Phone (390 px)**"), md.index("**Tablet (768 px)**"))
        self.assertLess(md.index("**Tablet (768 px)**"), md.index("**Desktop (1280 px)**"))
        self.assertIn("![Budget at phone width](https://raw.githubusercontent.com/AnthonyPluth/waypoint/pr-screenshots/pr-42/budget-phone-top.png)", md)
        self.assertIn("![Setup at phone width]", md)
        self.assertTrue(md.startswith("## Screenshots (`make verify`, made-up demo data, light theme)"))
        self.assertIn("Not checked: the dark theme (`make verify` captures light only)", md)
        self.assertTrue(md.endswith("---\n_Generated by [Claude Code](https://claude.ai/code)_\n"))

    def test_the_other_theme_is_the_one_not_checked(self):
        md = ps.comment_markdown(1, ["a-phone-top.png"], theme="dark")
        self.assertIn("dark theme)", md)
        self.assertIn("Not checked: the light theme.", md)

    def test_a_file_without_a_width_goes_under_other(self):
        md = ps.comment_markdown(1, ["flow-x-open.png"])
        self.assertIn("**Other**", md)
        self.assertNotIn("**Phone", md)

    def test_alt_text_names_page_and_width(self):
        self.assertEqual(ps.alt_text("flow-emoji-open-desktop-top.png"), "Flow emoji open at desktop width")
        self.assertEqual(ps.alt_text("odd.png"), "Odd")


class Selection(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.dir = Path(tmp.name)
        for n in ("a-phone.png", "a-phone-top.png", "b-tablet-top.png", "notes.txt"):
            (self.dir / n).write_bytes(b"x")

    def test_default_is_every_top_screenshot_not_the_full_page_ones(self):
        self.assertEqual([p.name for p in ps.select_files([], self.dir)], ["a-phone-top.png", "b-tablet-top.png"])

    def test_named_files_are_used_as_given(self):
        self.assertEqual(ps.select_files([str(self.dir / "a-phone.png")], self.dir), [self.dir / "a-phone.png"])

    def test_refuses_nothing_missing_and_non_png_files(self):
        with self.assertRaisesRegex(ps.ScreenshotError, "no \\*-top.png"):
            ps.select_files([], self.dir / "empty")
        with self.assertRaisesRegex(ps.ScreenshotError, "doesn't exist"):
            ps.select_files([str(self.dir / "gone.png")], self.dir)
        with self.assertRaisesRegex(ps.ScreenshotError, "isn't a .png"):
            ps.select_files([str(self.dir / "notes.txt")], self.dir)

    def test_only_screenshots_in_the_verify_folder_are_published(self):
        elsewhere = self.dir / "elsewhere"
        elsewhere.mkdir()
        (elsewhere / "real-instance.png").write_bytes(b"x")
        with self.assertRaisesRegex(ps.ScreenshotError, "only `make verify`'s screenshots"):
            ps.select_files([str(elsewhere / "real-instance.png")], self.dir)
        link = self.dir / "looks-fine-top.png"
        link.symlink_to(elsewhere / "real-instance.png")
        with self.assertRaisesRegex(ps.ScreenshotError, "only `make verify`'s screenshots"):
            ps.select_files([str(link)], self.dir)
        with self.assertRaisesRegex(ps.ScreenshotError, "only `make verify`'s screenshots"):
            ps.select_files([str(self.dir / "elsewhere" / ".." / ".." / "x-top.png")], self.dir)


class Arguments(unittest.TestCase):
    def test_parses_pr_files_and_theme(self):
        a = ps.parse_args(["7", "x.png", "--theme", "light", "--trailer", "A: b"])
        self.assertEqual((a.pr, a.files, a.theme, a.trailer), (7, ["x.png"], "light", ["A: b"]))

    def test_rejects_a_bad_pr_number(self):
        for bad in (["0"], ["abc"], []):
            with redirect_stderr(io.StringIO()), self.assertRaises(SystemExit):
                ps.parse_args(bad)

    def test_trailers_come_from_the_environment_then_flags(self):
        self.assertEqual(ps.trailers_from({"PR_SCREENSHOTS_TRAILERS": "A: 1\n\nB: 2\n"}, ["C: 3"]), ["A: 1", "B: 2", "C: 3"])
        self.assertEqual(ps.trailers_from({}, []), [])

    def test_a_commit_without_a_trailer_naming_the_model_is_refused(self):
        ps.check_trailers(TRAILERS)
        for bad in ([], ["Claude-Session: https://example.test/s"], ["Co-Authored-By: Claude <noreply@anthropic.com>"],
                    ["Co-Authored-By: Claude Test <noreply@anthropic.com>"], ["Co-Authored-By: Claude Test 1 <noreply@anthropic.com>"],
                    TRAILERS[:1] * 2):
            with self.assertRaisesRegex(ps.ScreenshotError, "naming the model"):
                ps.check_trailers(bad)

    def test_commit_message_ends_with_the_trailers(self):
        self.assertTrue(ps.commit_message(5, TRAILERS).endswith("\n".join(TRAILERS) + "\n"))

    def test_refuses_to_run_outside_the_repository(self):
        with tempfile.TemporaryDirectory() as elsewhere, redirect_stderr(io.StringIO()) as err, redirect_stdout(io.StringIO()):
            self.assertEqual(ps.main(["1", "x.png"], cwd=Path(elsewhere)), 2)
        self.assertIn("inside the Waypoint repository", err.getvalue())


class Publishing(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        base = Path(tmp.name)
        self.remote = base / "remote.git"
        run(base, "init", "--bare", "-b", "main", str(self.remote))
        self.repo = base / "repo"
        run(base, "clone", "-q", str(self.remote), str(self.repo))
        for k, v in (("user.name", "Test"), ("user.email", "test@example.test")):
            run(self.repo, "config", k, v)
        (self.repo / "app.txt").write_text("app\n")
        run(self.repo, "add", ".")
        run(self.repo, "commit", "-q", "-m", "init")
        run(self.repo, "push", "-q", "origin", "HEAD:main")
        self.shots = base / "shots"
        self.shots.mkdir()
        self.waits = []

    def shot(self, name, data=b"png"):
        p = self.shots / name
        p.write_bytes(data)
        return p

    def test_publish_without_a_model_trailer_is_refused_before_anything_is_pushed(self):
        with self.assertRaisesRegex(ps.ScreenshotError, "naming the model"):
            ps.publish(self.repo, 5, [self.shot("a-phone-top.png")], "origin", sleep=self.waits.append, log=lambda m: None)
        self.assertEqual(run(self.remote, "branch", "--list", ps.BRANCH).strip(), "")
        self.assertEqual(self.waits, [])

    def publish(self, pr, files):
        return ps.publish(self.repo, pr, files, "origin", TRAILERS, sleep=self.waits.append, log=lambda m: None)

    def remote_files(self):
        return run(self.remote, "ls-tree", "-r", "--name-only", ps.BRANCH).split()

    def test_creates_the_orphan_branch_with_a_readme_and_leaves_the_checkout_alone(self):
        before = (run(self.repo, "rev-parse", "HEAD"), run(self.repo, "branch", "--show-current"), run(self.repo, "branch", "--list"))
        self.assertTrue(self.publish(311, [self.shot("t-phone-top.png"), self.shot("t-tablet-top.png")]))
        self.assertEqual(self.remote_files(), ["README.md", "pr-311/t-phone-top.png", "pr-311/t-tablet-top.png"])
        self.assertEqual(run(self.remote, "rev-list", "--max-parents=0", ps.BRANCH).count("\n"), 1)   # parentless: an orphan
        self.assertTrue(run(self.remote, "log", "-1", "--format=%B", ps.BRANCH).strip().endswith(TRAILERS[-1]))
        after = (run(self.repo, "rev-parse", "HEAD"), run(self.repo, "branch", "--show-current"), run(self.repo, "branch", "--list"))
        self.assertEqual(before, after)
        self.assertEqual(run(self.repo, "status", "--porcelain"), "")
        self.assertEqual(run(self.repo, "worktree", "list").strip().count("\n"), 0)   # the temporary worktree is gone
        self.assertNotIn("app.txt", self.remote_files())

    def test_rerunning_replaces_that_prs_folder_and_keeps_other_prs(self):
        self.publish(1, [self.shot("a-phone-top.png", b"one")])
        self.publish(2, [self.shot("a-phone-top.png", b"two")])
        self.publish(1, [self.shot("b-phone-top.png", b"three")])
        self.assertEqual(self.remote_files(), ["README.md", "pr-1/b-phone-top.png", "pr-2/a-phone-top.png"])
        self.assertEqual(run(self.remote, "show", f"{ps.BRANCH}:pr-2/a-phone-top.png"), "two")

    def test_publishing_the_same_files_again_pushes_nothing(self):
        files = [self.shot("a-phone-top.png")]
        self.assertTrue(self.publish(9, files))
        head = run(self.remote, "rev-parse", ps.BRANCH)
        self.assertFalse(self.publish(9, files))
        self.assertEqual(run(self.remote, "rev-parse", ps.BRANCH), head)

    def test_a_failing_push_is_retried_then_reported_and_never_forced(self):
        run(self.repo, "remote", "set-url", "origin", str(self.remote.parent / "nowhere.git"))
        with self.assertRaisesRegex(ps.ScreenshotError, "git ls-remote"):
            self.publish(3, [self.shot("a-phone-top.png")])
        self.assertEqual(self.waits, [2, 4, 8])

    def test_a_branch_someone_else_moved_meanwhile_is_built_on_not_overwritten(self):
        self.publish(1, [self.shot("a-phone-top.png")])
        other = self.remote.parent / "other"
        run(self.remote.parent, "clone", "-q", "-b", ps.BRANCH, str(self.remote), str(other))
        for k, v in (("user.name", "T"), ("user.email", "t@example.test")):
            run(other, "config", k, v)
        (other / "pr-8").mkdir()
        (other / "pr-8" / "x.png").write_bytes(b"x")
        run(other, "add", ".")
        run(other, "commit", "-q", "-m", "other")
        run(other, "push", "-q", "origin", ps.BRANCH)
        self.publish(2, [self.shot("b-phone-top.png")])
        self.assertEqual(self.remote_files(), ["README.md", "pr-1/a-phone-top.png", "pr-2/b-phone-top.png", "pr-8/x.png"])


if __name__ == "__main__":
    unittest.main()
