from __future__ import annotations

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERIFY_DIR = ROOT / "artifacts" / "verify"
BRANCH = "pr-screenshots"
REPO_SLUG = "AnthonyPluth/waypoint"
WIDTHS = {"phone": 390, "tablet": 768, "desktop": 1280}
_spec = importlib.util.spec_from_file_location("fleet_checks", Path(__file__).resolve().parent / "fleet_checks.py")
assert _spec and _spec.loader
fleet_checks = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fleet_checks)
FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_"
README = (
    "# PR screenshots\n\n"
    "Screenshots from `make verify` (made-up demo data only) that pull requests embed in a comment, one folder per pull "
    "request (`pr-<number>/`). Written by `make pr-screenshots`; this branch is not part of any pull request's diff.\n"
)
PUSH_ATTEMPTS = 4
EXIT_REF_MISSING = 2


class ScreenshotError(Exception):
    pass


def raw_url(pr: int, name: str, slug: str = REPO_SLUG) -> str:
    return f"https://raw.githubusercontent.com/{slug}/{BRANCH}/pr-{pr}/{name}"


def viewport_of(name: str) -> str | None:
    m = re.search(r"-(phone|tablet|desktop)(?:-top)?\.png$", name)
    return m.group(1) if m else None


def alt_text(name: str) -> str:
    viewport = viewport_of(name)
    page = re.sub(r"-(?:phone|tablet|desktop)(?:-top)?\.png$|-top\.png$|\.png$", "", name).replace("-", " ").replace("_", " ")
    page = page[:1].upper() + page[1:]
    return f"{page} at {viewport} width" if viewport else page


def select_files(paths: Sequence[str], verify_dir: Path = VERIFY_DIR) -> list[Path]:
    chosen = [Path(p) for p in paths] if paths else sorted(verify_dir.glob("*-top.png"))
    for p in chosen:
        if p.resolve().parent != verify_dir.resolve():
            raise ScreenshotError(f"{p} isn't in {verify_dir}: only `make verify`'s screenshots, taken on made-up demo data, are published "
                                  "(the branch is public)")
    if not chosen:
        raise ScreenshotError(f"no *-top.png screenshots in {verify_dir}: run `make verify` first (or name the files)")
    for p in chosen:
        if p.suffix.lower() != ".png":
            raise ScreenshotError(f"{p} isn't a .png file")
        if not p.is_file():
            raise ScreenshotError(f"{p} doesn't exist")
    return chosen


def comment_markdown(pr: int, names: Sequence[str], theme: str = "dark", slug: str = REPO_SLUG) -> str:
    groups: dict[str, list[str]] = {}
    for name in sorted(names):
        groups.setdefault(viewport_of(name) or "other", []).append(name)
    out = [f"## Screenshots (`make verify`, made-up demo data, {theme} theme)", ""]
    for key in (*WIDTHS, "other"):
        if key not in groups:
            continue
        out += [f"**{key.capitalize()} ({WIDTHS[key]} px)**" if key in WIDTHS else "**Other**", ""]
        out += [f"![{alt_text(n)}]({raw_url(pr, n, slug)})\n" for n in groups[key]]
    out.append(FOOTER)
    return "\n".join(out) + "\n"


def trailers_from(env: dict[str, str], extra: Sequence[str]) -> list[str]:
    lines = [t.strip() for t in env.get("PR_SCREENSHOTS_TRAILERS", "").splitlines() if t.strip()]
    lines += [t.strip() for t in extra if t.strip()]
    return lines


def check_trailers(trailers: Sequence[str]) -> None:
    claude = [v for k, _, v in (t.partition(":") for t in trailers) if k.strip().lower() == "co-authored-by" and v.strip().startswith("Claude")]
    if len(claude) != 1 or not fleet_checks.GOOD_CO_AUTHOR.match(claude[0].strip()):
        raise ScreenshotError("no commit trailer naming the model: set $PR_SCREENSHOTS_TRAILERS (one per line) or pass --trailer, "
                              "with `Co-Authored-By: Claude <Model> <version> <noreply@anthropic.com>` among them, as in your own commits")


def commit_message(pr: int, trailers: Sequence[str]) -> str:
    return f"Add screenshots for PR #{pr}\n\nMade-up demo data from `make verify`.\n\n" + "\n".join(trailers) + "\n"


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(prog="pr_screenshots.py", description="Publish make verify screenshots for a PR and print its comment.")
    ap.add_argument("pr", type=int, help="the pull request's number")
    ap.add_argument("files", nargs="*", help="screenshots to publish (default: every *-top.png in artifacts/verify/)")
    ap.add_argument("--theme", choices=("dark", "light"), default="dark", help="the theme the screenshots show (default dark; Waypoint is dark only)")
    ap.add_argument("--trailer", action="append", default=[], help="a commit trailer, 'Key: value' (repeatable)")
    ap.add_argument("--remote", default="origin", help=argparse.SUPPRESS)
    args = ap.parse_args(argv)
    if args.pr < 1:
        ap.error("the pull request number must be positive")
    return args


def git(cwd: Path, *args: str, ok: Sequence[int] = (0,)) -> subprocess.CompletedProcess[str]:
    done = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)
    if done.returncode not in ok:
        raise ScreenshotError(f"git {' '.join(args)} failed ({done.returncode}): {(done.stderr or done.stdout).strip()}")
    return done


def inside(path: Path, root: Path = ROOT) -> bool:
    return path.resolve() == root or root in path.resolve().parents


def _attempt(repo: Path, pr: int, files: Sequence[Path], remote: str, message: str, tmp: Path) -> bool:
    work = tmp / "wt"
    local = f"pr-screenshots-tmp-{os.getpid()}"
    exists = git(repo, "ls-remote", "--exit-code", "--heads", remote, BRANCH, ok=(0, EXIT_REF_MISSING)).returncode == 0
    try:
        if exists:
            git(repo, "fetch", "--quiet", remote, BRANCH)
            git(repo, "worktree", "add", "--quiet", "--detach", str(work), "FETCH_HEAD")
        else:
            git(repo, "worktree", "add", "--quiet", "--detach", str(work), "HEAD")
            git(work, "checkout", "--quiet", "--orphan", local)
            git(work, "rm", "-rf", "--quiet", "--ignore-unmatch", ".")
            (work / "README.md").write_text(README)
            git(work, "add", "README.md")
        folder = work / f"pr-{pr}"
        shutil.rmtree(folder, ignore_errors=True)
        folder.mkdir()
        for f in files:
            shutil.copyfile(f, folder / f.name)
        git(work, "add", "-A", "--", ".")
        if not git(work, "status", "--porcelain").stdout.strip():
            return False
        git(work, "commit", "--quiet", "-m", message)
        git(work, "push", remote, f"HEAD:refs/heads/{BRANCH}")
        return True
    finally:
        subprocess.run(["git", "worktree", "remove", "--force", str(work)], cwd=repo, capture_output=True, text=True)
        subprocess.run(["git", "worktree", "prune"], cwd=repo, capture_output=True, text=True)
        subprocess.run(["git", "branch", "-D", local], cwd=repo, capture_output=True, text=True)


def publish(repo: Path, pr: int, files: Sequence[Path], remote: str = "origin", trailers: Sequence[str] = (),
            sleep: Callable[[float], None] = time.sleep, log: Callable[[str], None] = lambda m: print(m, file=sys.stderr)) -> bool:
    check_trailers(trailers)
    message = commit_message(pr, trailers)
    for attempt in range(1, PUSH_ATTEMPTS):
        with tempfile.TemporaryDirectory(prefix="pr-screenshots-") as tmp:
            try:
                return _attempt(repo, pr, files, remote, message, Path(tmp))
            except ScreenshotError as e:
                wait = 2 ** attempt
                log(f"pr_screenshots: attempt {attempt} failed ({e}); retrying in {wait}s")
                sleep(wait)
    with tempfile.TemporaryDirectory(prefix="pr-screenshots-") as tmp:
        return _attempt(repo, pr, files, remote, message, Path(tmp))


def main(argv: Sequence[str], cwd: Path | None = None, env: dict[str, str] | None = None) -> int:
    args = parse_args(argv)
    here = (cwd or Path.cwd()).resolve()
    if not inside(here):
        print(f"pr_screenshots: run this inside the Waypoint repository ({ROOT}), not {here}", file=sys.stderr)
        return 2
    try:
        files = select_files(args.files)
        pushed = publish(ROOT, args.pr, files, args.remote, trailers_from(env if env is not None else dict(os.environ), args.trailer))
    except ScreenshotError as e:
        print(f"pr_screenshots: {e}", file=sys.stderr)
        return 1
    print(f"pr_screenshots: {'pushed' if pushed else 'already up to date:'} {len(files)} file(s) in {BRANCH}/pr-{args.pr}/", file=sys.stderr)
    print(comment_markdown(args.pr, [f.name for f in files], args.theme))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
