// The API contract's types: the request bodies and replies of the routes waypoint/server/contract.py covers.
// Generated by tools/api_contract.py from docs/openapi.json (`make api-contract`); don't edit by hand.
// lib/contract.ts's apiCall() types a call by its route, as Endpoints names it: apiCall<"GET /api/budget">(address).

export interface BackupContents {
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  current: Record<string, number>;
  database: "sqlite" | "postgres";
}

export interface Restored {
  ok: boolean;
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  safety_copy: string | null;
  unreadable_secrets: string[];
}

/** Who's signed in. Without sign-in configured (on your own machine), everyone is `local`. */
export interface SignedIn {
  name: string | null;
  email: string | null;
  sub?: string;
  local?: boolean;
}

export interface State {
  version: string;
  database: "sqlite" | "postgres";
  user: SignedIn | null;
  sentry: Record<string, unknown> | null;
  last_backup: string | null;
}

/** Each covered route ("METHOD /path", as in waypoint/server/routes.py): what it takes and what it answers. */
export interface Endpoints {
  "POST /api/backup/inspect": { body: never; reply: BackupContents };
  "POST /api/restore": { body: never; reply: Restored };
  "GET /api/state": { body: never; reply: State };
}
