// The API contract's types: the request bodies and replies of the routes waypoint/server/contract.py covers.
// Generated by tools/api_contract.py from docs/openapi.json (`make api-contract`); don't edit by hand.
// lib/contract.ts's apiCall() types a call by its route, as Endpoints names it: apiCall<"GET /api/budget">(address).

/** Settings → AI. A field left out stays as it was; `openrouter_key: ""` forgets the saved key. */
export interface AiBody {
  mode: "off" | "local" | "openrouter";
  ollama_url?: string;
  ollama_model?: string;
  openrouter_model?: string;
  openrouter_key?: string;
}

export interface AiSettings {
  mode: "off" | "local" | "openrouter";
  ollama_url: string;
  ollama_model: string;
  openrouter_model: string;
  key: "env" | "saved" | null;
}

/** The booking's fields the AI read, as the Add by hand form has them. A flight has no zones: its airports give them. */
export interface AiSuggestion {
  kind: "flight" | "hotel" | "car" | "train";
  origin: string;
  start_local: string;
  end_local: string;
  provider?: string;
  confirmation?: string;
  destination?: string;
  start_zone?: string;
  end_zone?: string;
}

export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
  zone: string;
}

export interface BackupContents {
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  current: Record<string, number>;
  database: "sqlite" | "postgres";
}

export interface Disconnected {
  ok: boolean;
  revoked: boolean;
}

/**
 * A flight's live status, shown beside its booked times (the booking is never changed). Times are `2026-03-01T22:15`
 * wall-clock times at the airports, in their zones (`dep_zone`, `arr_zone`), never converted.
 */
export interface FlightStatus {
  segment_id: number;
  state: "scheduled" | "delayed" | "departed" | "landed" | "cancelled" | "diverted";
  origin: string | null;
  destination: string | null;
  dep_scheduled: string | null;
  dep_estimated: string | null;
  dep_actual: string | null;
  dep_zone: string;
  dep_terminal: string | null;
  dep_gate: string | null;
  arr_scheduled: string | null;
  arr_estimated: string | null;
  arr_actual: string | null;
  arr_zone: string;
  arr_terminal: string | null;
  arr_gate: string | null;
  delay_minutes: number | null;
  fetched_at: string;
}

export interface FlightStatusList {
  enabled: boolean;
  month: string;
  used: number;
  limit: number;
  paused: FlightStatusPause | null;
  statuses: FlightStatus[];
}

export interface FlightStatusPause {
  until: string;
  reason: "limit" | "rate" | "key";
}

/** A membership, to save or to change. `number` is needed to save one; left out when changing, the saved one is kept. */
export interface LoyaltyBody {
  person_id: number;
  kind: string;
  program: string;
  number?: string | null;
  tier?: string | null;
  expiry?: string | null;
  notes?: string | null;
}

/** One membership. The number comes only masked (its last four characters); `POST /api/loyalty/{id}/reveal` gives it. */
export interface LoyaltyEntry {
  id: number;
  person_id: number;
  kind: string;
  program: string;
  masked: string;
  readable: boolean;
  tier: string | null;
  expiry: string | null;
  notes: string | null;
}

export interface LoyaltyList {
  loyalty: LoyaltyEntry[];
  programs: Record<string, string[]>;
}

export interface Mailbox {
  id: number;
  address: string;
  status: "connected" | "reconnect" | "error";
  last_error: string | null;
  last_scan: string | null;
  scan_error: string | null;
  scanning: boolean;
}

export interface MailboxList {
  configured: boolean;
  mailboxes: Mailbox[];
}

export interface Matched {
  ok: boolean;
  matched: number;
}

export interface MergeBody {
  merge: number;
}

export interface Ok {
  ok: boolean;
}

export interface People {
  people: Person[];
}

/** Someone who travels: a household member (`member`, linked to their sign-in) or a guest with no login. */
export interface Person {
  id: number;
  display_name: string;
  first_name: string | null;
  legal_name: string | null;
  aliases: string[];
  member: boolean;
}

/**
 * A person's names, to add a guest or to change anyone's (a member's link to their login can't be changed). Changing
 * replaces all of them, so send every name to keep: one left out is cleared.
 */
export interface PersonBody {
  display_name: string;
  first_name?: string | null;
  legal_name?: string | null;
  aliases?: string[];
}

export interface Restored {
  ok: boolean;
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  safety_copy: string | null;
  unreadable_secrets: string[];
}

export interface Revealed {
  number: string;
}

export interface Review {
  items: ReviewItem[];
  who: WhoIsThis[];
}

/**
 * One message Waypoint couldn't read, for the member whose mailbox it is. Never its subject or text: only who it
 * came from and its day (Open in Gmail shows the message).
 */
export interface ReviewItem {
  id: number;
  address: string;
  sender_domain: string;
  received: string | null;
  reason: "no_markup" | "incomplete" | "broken";
  gmail_url: string;
  suggestion: AiSuggestion | null;
  suggestion_error: string | null;
}

export interface ScanStarted {
  started: boolean;
}

/**
 * One flight leg, hotel stay, car rental or train. Its times are local wall-clock times at the place, never
 * converted: `start_local` is 2026-03-01T22:15 in `start_zone`, whatever zone the server or the viewer is in.
 */
export interface Segment {
  id: number;
  trip_id: number;
  kind: "flight" | "hotel" | "car" | "train";
  status: "confirmed" | "changed" | "cancelled";
  confirmation: string | null;
  provider: string | null;
  start_local: string;
  start_zone: string;
  end_local: string;
  end_zone: string;
  origin: string | null;
  destination: string | null;
  details: Record<string, string>;
  manage_url: string | null;
  source: "manual" | "email";
  booked_by: number | null;
  locked_fields: string[];
  travelers: Traveler[];
}

/**
 * A segment to add; `trip_id` leaves it to Waypoint to group it into a trip. A flight's zones come from its airports
 * unless given.
 */
export interface SegmentBody {
  kind: "flight" | "hotel" | "car" | "train";
  start_local: string;
  end_local: string;
  trip_id?: number | null;
  status?: "confirmed" | "changed" | "cancelled";
  confirmation?: string | null;
  provider?: string | null;
  start_zone?: string | null;
  end_zone?: string | null;
  origin?: string | null;
  destination?: string | null;
  details?: Record<string, string>;
  manage_url?: string | null;
  travelers?: TravelerBody[];
}

/** What to change on a segment: only the fields sent. The ones that end up different are locked. */
export interface SegmentEdit {
  kind?: "flight" | "hotel" | "car" | "train";
  status?: "confirmed" | "changed" | "cancelled";
  confirmation?: string | null;
  provider?: string | null;
  start_local?: string;
  start_zone?: string | null;
  end_local?: string;
  end_zone?: string | null;
  origin?: string | null;
  destination?: string | null;
  details?: Record<string, string>;
  manage_url?: string | null;
  travelers?: TravelerBody[];
}

/** Who's signed in. Without sign-in configured (on your own machine), everyone is `local`. */
export interface SignedIn {
  name: string | null;
  email: string | null;
  sub?: string;
  local?: boolean;
}

export interface SplitBody {
  segment_ids: number[];
}

export interface Started {
  url: string;
}

export interface State {
  version: string;
  database: "sqlite" | "postgres";
  user: SignedIn | null;
  last_backup: string | null;
  review_count: number;
}

export interface Traveler {
  id: number;
  person_id: number | null;
  name: string;
}

export interface TravelerBody {
  person_id?: number | null;
  name?: string | null;
}

export interface Trip {
  id: number;
  name: string;
  start_date: string | null;
  end_date: string | null;
  destination: string | null;
  notes: string | null;
  auto: boolean;
  booked_by: number | null;
  segments: Segment[];
}

/** A trip made by hand, or what changes on one (a name, where it goes, notes; its dates come from its segments). */
export interface TripBody {
  name?: string;
  destination?: string | null;
  notes?: string | null;
  start_date?: string | null;
  end_date?: string | null;
}

export interface TripList {
  trips: Trip[];
}

/** Who a printed name is: a person in People, or a name to add as a guest. Send one. */
export interface WhoBody {
  person_id?: number;
  new_guest?: string;
}

/** A name on a booking that isn't matched to a person, with the segment it's on. */
export interface WhoIsThis {
  id: number;
  name: string;
  segment_id: number;
  trip_id: number;
  kind: "flight" | "hotel" | "car" | "train";
  provider: string | null;
  origin: string | null;
  destination: string | null;
  start_local: string;
  start_zone: string;
}

/** Each covered route ("METHOD /path", as in waypoint/server/routes.py): what it takes and what it answers. */
export interface Endpoints {
  "GET /api/ai": { body: never; reply: AiSettings };
  "POST /api/ai": { body: AiBody; reply: AiSettings };
  "POST /api/backup/inspect": { body: never; reply: BackupContents };
  "POST /api/restore": { body: never; reply: Restored };
  "GET /api/people": { body: never; reply: People };
  "POST /api/people": { body: PersonBody; reply: Person };
  "POST /api/people/{id}": { body: PersonBody; reply: Person };
  "DELETE /api/people/{id}": { body: never; reply: Ok };
  "GET /api/trips": { body: never; reply: TripList };
  "POST /api/trips": { body: TripBody; reply: Trip };
  "GET /api/trips/{id}": { body: never; reply: Trip };
  "POST /api/trips/{id}": { body: TripBody; reply: Trip };
  "DELETE /api/trips/{id}": { body: never; reply: Ok };
  "POST /api/trips/{id}/merge": { body: MergeBody; reply: Trip };
  "POST /api/trips/{id}/split": { body: SplitBody; reply: Trip };
  "POST /api/segments": { body: SegmentBody; reply: Segment };
  "GET /api/segments/{id}": { body: never; reply: Segment };
  "POST /api/segments/{id}": { body: SegmentEdit; reply: Segment };
  "DELETE /api/segments/{id}": { body: never; reply: Ok };
  "GET /api/airports/{id}": { body: never; reply: Airport };
  "GET /api/flight-status": { body: never; reply: FlightStatusList };
  "POST /api/flight-status/{id}": { body: never; reply: FlightStatusList };
  "GET /api/loyalty": { body: never; reply: LoyaltyList };
  "POST /api/loyalty": { body: LoyaltyBody; reply: LoyaltyEntry };
  "POST /api/loyalty/{id}": { body: LoyaltyBody; reply: LoyaltyEntry };
  "DELETE /api/loyalty/{id}": { body: never; reply: Ok };
  "POST /api/loyalty/{id}/reveal": { body: never; reply: Revealed };
  "GET /api/mailboxes": { body: never; reply: MailboxList };
  "POST /api/mailboxes/connect": { body: never; reply: Started };
  "DELETE /api/mailboxes/{id}": { body: never; reply: Disconnected };
  "POST /api/mailboxes/{id}/scan": { body: never; reply: ScanStarted };
  "GET /api/review": { body: never; reply: Review };
  "POST /api/review/who/{id}": { body: WhoBody; reply: Matched };
  "POST /api/review/{id}/ignore": { body: never; reply: Ok };
  "DELETE /api/review/{id}": { body: never; reply: Ok };
  "GET /api/state": { body: never; reply: State };
}
