// The API contract's types: the request bodies and replies of the routes waypoint/server/contract.py covers.
// Generated by tools/api_contract.py from docs/openapi.json (`make api-contract`); don't edit by hand.
// lib/contract.ts's apiCall() types a call by its route, as Endpoints names it: apiCall<"GET /api/budget">(address).

export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
  zone: string;
}

export interface BackupContents {
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  current: Record<string, number>;
  database: "sqlite" | "postgres";
}

export interface Disconnected {
  ok: boolean;
  revoked: boolean;
}

export interface Mailbox {
  id: number;
  address: string;
  status: "connected" | "reconnect" | "error";
  last_error: string | null;
  last_scan: string | null;
}

export interface MailboxList {
  configured: boolean;
  mailboxes: Mailbox[];
}

export interface MergeBody {
  merge: number;
}

export interface Ok {
  ok: boolean;
}

export interface People {
  people: Person[];
}

/** Someone who travels: a household member (`member`, linked to their sign-in) or a guest with no login. */
export interface Person {
  id: number;
  display_name: string;
  first_name: string | null;
  legal_name: string | null;
  aliases: string[];
  member: boolean;
}

/** A person's names, to add a guest or to change anyone's (a member's link to their login can't be changed). */
export interface PersonBody {
  display_name: string;
  first_name?: string | null;
  legal_name?: string | null;
  aliases?: string[];
}

export interface Restored {
  ok: boolean;
  created: string | null;
  source: string | null;
  counts: Record<string, number>;
  safety_copy: string | null;
  unreadable_secrets: string[];
}

/**
 * One flight leg, hotel stay, car rental or train. Its times are local wall-clock times at the place, never
 * converted: `start_local` is 2026-03-01T22:15 in `start_zone`, whatever zone the server or the viewer is in.
 */
export interface Segment {
  id: number;
  trip_id: number;
  kind: "flight" | "hotel" | "car" | "train";
  status: "confirmed" | "changed" | "cancelled";
  confirmation: string | null;
  provider: string | null;
  start_local: string;
  start_zone: string;
  end_local: string;
  end_zone: string;
  origin: string | null;
  destination: string | null;
  details: Record<string, string>;
  manage_url: string | null;
  source: "manual" | "email";
  booked_by: number | null;
  locked_fields: string[];
  travelers: Traveler[];
}

/**
 * A segment to add; `trip_id` leaves it to Waypoint to group it into a trip. A flight's zones come from its airports
 * unless given.
 */
export interface SegmentBody {
  kind: "flight" | "hotel" | "car" | "train";
  start_local: string;
  end_local: string;
  trip_id?: number | null;
  status?: "confirmed" | "changed" | "cancelled";
  confirmation?: string | null;
  provider?: string | null;
  start_zone?: string | null;
  end_zone?: string | null;
  origin?: string | null;
  destination?: string | null;
  details?: Record<string, string>;
  manage_url?: string | null;
  travelers?: TravelerBody[];
}

/** What to change on a segment: only the fields sent. The ones that end up different are locked. */
export interface SegmentEdit {
  kind?: "flight" | "hotel" | "car" | "train";
  status?: "confirmed" | "changed" | "cancelled";
  confirmation?: string | null;
  provider?: string | null;
  start_local?: string;
  start_zone?: string | null;
  end_local?: string;
  end_zone?: string | null;
  origin?: string | null;
  destination?: string | null;
  details?: Record<string, string>;
  manage_url?: string | null;
  travelers?: TravelerBody[];
}

/** Who's signed in. Without sign-in configured (on your own machine), everyone is `local`. */
export interface SignedIn {
  name: string | null;
  email: string | null;
  sub?: string;
  local?: boolean;
}

export interface SplitBody {
  segment_ids: number[];
}

export interface Started {
  url: string;
}

export interface State {
  version: string;
  database: "sqlite" | "postgres";
  user: SignedIn | null;
  last_backup: string | null;
}

export interface Traveler {
  id: number;
  person_id: number | null;
  name: string;
}

export interface TravelerBody {
  person_id?: number | null;
  name?: string | null;
}

export interface Trip {
  id: number;
  name: string;
  start_date: string | null;
  end_date: string | null;
  destination: string | null;
  notes: string | null;
  auto: boolean;
  booked_by: number | null;
  segments: Segment[];
}

/** A trip made by hand, or what changes on one (a name, where it goes, notes; its dates come from its segments). */
export interface TripBody {
  name?: string;
  destination?: string | null;
  notes?: string | null;
  start_date?: string | null;
  end_date?: string | null;
}

export interface TripList {
  trips: Trip[];
}

/** Each covered route ("METHOD /path", as in waypoint/server/routes.py): what it takes and what it answers. */
export interface Endpoints {
  "POST /api/backup/inspect": { body: never; reply: BackupContents };
  "POST /api/restore": { body: never; reply: Restored };
  "GET /api/people": { body: never; reply: People };
  "POST /api/people": { body: PersonBody; reply: Person };
  "POST /api/people/{id}": { body: PersonBody; reply: Person };
  "DELETE /api/people/{id}": { body: never; reply: Ok };
  "GET /api/trips": { body: never; reply: TripList };
  "POST /api/trips": { body: TripBody; reply: Trip };
  "GET /api/trips/{id}": { body: never; reply: Trip };
  "POST /api/trips/{id}": { body: TripBody; reply: Trip };
  "DELETE /api/trips/{id}": { body: never; reply: Ok };
  "POST /api/trips/{id}/merge": { body: MergeBody; reply: Trip };
  "POST /api/trips/{id}/split": { body: SplitBody; reply: Trip };
  "POST /api/segments": { body: SegmentBody; reply: Segment };
  "GET /api/segments/{id}": { body: never; reply: Segment };
  "POST /api/segments/{id}": { body: SegmentEdit; reply: Segment };
  "DELETE /api/segments/{id}": { body: never; reply: Ok };
  "GET /api/airports/{id}": { body: never; reply: Airport };
  "GET /api/mailboxes": { body: never; reply: MailboxList };
  "POST /api/mailboxes/connect": { body: never; reply: Started };
  "DELETE /api/mailboxes/{id}": { body: never; reply: Disconnected };
  "GET /api/state": { body: never; reply: State };
}
